#!/usr/bin/env python3
"""Initialize one object world pose from a capture-format frame.

This is the bridge between a raw capture episode (``videos/`` + ``cam_param/``)
and the FoundPose/GoTrack pipeline.  It consumes the PNGs written by
``src/process/mask.py --frame-index``:

    <frame-dir>/images/<serial>.png
    <frame-dir>/masks/<serial>.png

It estimates a FoundPose candidate independently for each visible camera,
selects a single world-frame pose by cross-view silhouette IoU, optionally
refines it, and saves ``init_pose_world.npy`` for GoTrack frame 0.

Run in the ``gotrack`` conda environment.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
from pathlib import Path

import cv2
import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

os.environ.setdefault("PYOPENGL_PLATFORM", "egl")
os.environ.setdefault("EGL_PLATFORM", "surfaceless")


def _as_4x4(value: object) -> np.ndarray:
    pose = np.asarray(value, dtype=np.float64)
    if pose.shape == (3, 4):
        pose = np.vstack([pose, [0.0, 0.0, 0.0, 1.0]])
    if pose.shape != (4, 4):
        raise ValueError(f"Expected a 3x4 or 4x4 extrinsic, got {pose.shape}")
    return pose


def load_frame_inputs(capture_dir: Path, frame_dir: Path):
    """Return RGB images, boolean masks, K matrices, and world-to-camera poses."""
    with open(capture_dir / "cam_param" / "intrinsics.json", encoding="utf-8") as f:
        intr_raw = json.load(f)
    with open(capture_dir / "cam_param" / "extrinsics.json", encoding="utf-8") as f:
        extr_raw = json.load(f)

    images_dir = frame_dir / "images"
    masks_dir = frame_dir / "masks"
    if not images_dir.is_dir() or not masks_dir.is_dir():
        raise FileNotFoundError(
            f"Expected images/ and masks/ under {frame_dir}. "
            "Run src/process/mask.py --frame-index first."
        )

    images_rgb: dict[str, np.ndarray] = {}
    masks_bool: dict[str, np.ndarray] = {}
    intrinsics: dict[str, np.ndarray] = {}
    extrinsics: dict[str, np.ndarray] = {}
    for image_path in sorted(images_dir.glob("*.png")):
        serial = image_path.stem
        mask_path = masks_dir / image_path.name
        if serial not in intr_raw or serial not in extr_raw or not mask_path.exists():
            continue
        bgr = cv2.imread(str(image_path), cv2.IMREAD_COLOR)
        mask = cv2.imread(str(mask_path), cv2.IMREAD_GRAYSCALE)
        if bgr is None or mask is None or mask.shape != bgr.shape[:2]:
            continue
        if int((mask > 127).sum()) == 0:
            continue
        images_rgb[serial] = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
        masks_bool[serial] = mask > 127
        intrinsics[serial] = np.asarray(
            intr_raw[serial]["intrinsics_undistort"], dtype=np.float64,
        ).reshape(3, 3)
        extrinsics[serial] = _as_4x4(extr_raw[serial])

    if not images_rgb:
        raise RuntimeError("No valid image/mask/calibration triples found.")
    first = next(iter(images_rgb.values()))
    return images_rgb, masks_bool, intrinsics, extrinsics, first.shape[:2]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--capture-dir", required=True,
                        help="Capture episode containing cam_param/.")
    parser.add_argument("--frame-dir", default=None,
                        help="Directory generated by mask.py --frame-index. Default: frame 0 output.")
    parser.add_argument("--mesh", required=True, help="Object mesh path (.obj/.ply/.glb).")
    parser.add_argument("--object-name", default=None,
                        help="FoundPose asset tag. Default: capture directory parent name.")
    parser.add_argument("--output-dir", default=None,
                        help="Default: <frame-dir>/foundpose_init/")
    parser.add_argument("--assets-root", default=None,
                        help="Default: <mesh parent>/foundpose_assets when present, otherwise "
                             "<capture parent>/foundpose_assets.")
    parser.add_argument("--device", default="cuda:0")
    parser.add_argument("--force-onboard", action="store_true")
    parser.add_argument("--skip-silhouette", action="store_true",
                        help="Save cross-view IoU pose without silhouette refinement.")
    parser.add_argument("--silhouette-iters", type=int, default=100)
    parser.add_argument("--pose-selection-mode", choices=("silhouette", "consensus", "hybrid"),
                        default="silhouette",
                        help="Candidate selector. silhouette preserves legacy behavior; consensus/hybrid use per-view FoundPose PnP agreement.")
    parser.add_argument("--pose-candidate-rank", type=int, default=0,
                        help="Use this zero-based rank from the selected candidate bank; useful for case studies.")
    parser.add_argument("--candidate-bank-size", type=int, default=3,
                        help="How many ranked candidates to save for inspection.")
    parser.add_argument("--consensus-rotation-deg", type=float, default=25.0)
    parser.add_argument("--consensus-translation-m", type=float, default=0.06)
    args = parser.parse_args()

    capture_dir = Path(args.capture_dir).expanduser().resolve()
    frame_dir = (Path(args.frame_dir).expanduser().resolve() if args.frame_dir else
                 capture_dir / "foundpose_frame_000000")
    mesh_path = Path(args.mesh).expanduser().resolve()
    output_dir = (Path(args.output_dir).expanduser().resolve() if args.output_dir else
                  frame_dir / "foundpose_init")
    # A campaign-local cache matches its calibration family. Fall back to the
    # mesh-local cache for existing captures that have no campaign cache yet.
    campaign_assets_root = capture_dir.parent / "foundpose_assets"
    mesh_assets_root = mesh_path.parent / "foundpose_assets"
    assets_root = (
        Path(args.assets_root).expanduser().resolve() if args.assets_root else
        mesh_assets_root if mesh_assets_root.is_dir() else
        campaign_assets_root
    )
    object_name = args.object_name or capture_dir.parent.name
    if not mesh_path.is_file():
        raise FileNotFoundError(f"Mesh not found: {mesh_path}")

    images, masks, intrinsics, extrinsics, (height, width) = load_frame_inputs(
        capture_dir, frame_dir,
    )
    serials = sorted(images)
    output_dir.mkdir(parents=True, exist_ok=True)
    print(f"[inputs] {len(serials)} valid views, {width}x{height}; object={object_name}", flush=True)

    from autodex.perception.foundpose_init import FoundPoseInit
    from autodex.perception.pose_select import rank_pose_candidates, select_best_pose_by_iou

    init = FoundPoseInit(
        mesh_path=str(mesh_path),
        assets_root=str(assets_root),
        obj_name=object_name,
        object_id=1,
        device=args.device,
        reference_intrinsics_json=str(capture_dir / "cam_param" / "intrinsics.json"),
        reference_camera_id=serials[0],
        force_onboard=args.force_onboard,
    )
    t0 = time.perf_counter()
    per_view = init.estimate_per_view(images, masks, intrinsics, extrinsics)
    foundpose_sec = time.perf_counter() - t0
    candidates = {s: item["pose_world"] for s, item in per_view.items() if item is not None}
    if not candidates:
        raise RuntimeError("FoundPose failed in every camera view.")
    print(f"[foundpose] {len(candidates)}/{len(serials)} candidate poses ({foundpose_sec:.1f}s)", flush=True)

    from autodex.perception.silhouette import SilhouetteOptimizer
    sil = SilhouetteOptimizer(str(mesh_path), device=args.device)
    best_serial, legacy_pose, legacy_mean_iou, per_candidate_iou = select_best_pose_by_iou(
        candidates=candidates,
        masks=masks,
        intrinsics=intrinsics,
        extrinsics=extrinsics,
        H=height,
        W=width,
        glctx=sil.glctx,
        mesh_tensors=sil.mesh_tensors,
    )
    if legacy_pose is None:
        raise RuntimeError("Cross-view IoU pose selection failed.")

    candidate_bank = rank_pose_candidates(
        candidates=candidates,
        pnp_quality={serial: float(per_view[serial]["quality"]) for serial in candidates},
        iou_scores=per_candidate_iou,
        consensus_rotation_deg=args.consensus_rotation_deg,
        consensus_translation_m=args.consensus_translation_m,
    )
    if args.pose_selection_mode == "silhouette":
        selected = sorted(candidate_bank, key=lambda item: item["mean_iou"], reverse=True)
    elif args.pose_selection_mode == "consensus":
        selected = sorted(candidate_bank, key=lambda item: item["consensus"], reverse=True)
    else:
        selected = sorted(candidate_bank, key=lambda item: item["hybrid_score"], reverse=True)
    if args.pose_candidate_rank < 0 or args.pose_candidate_rank >= len(selected):
        raise ValueError(f"--pose-candidate-rank must be in [0, {len(selected) - 1}]")
    chosen = selected[args.pose_candidate_rank]
    pose_pre = np.asarray(chosen["pose_world"], dtype=np.float64)
    mean_iou = float(chosen["mean_iou"])
    best_serial = str(chosen["source_serial"])
    serializable_bank = [{
        **{key: value for key, value in item.items() if key != "pose_world"},
        "pose_world": np.asarray(item["pose_world"]).tolist(),
    } for item in selected[:max(1, args.candidate_bank_size)]]
    (output_dir / "candidate_bank.json").write_text(json.dumps({
        "selection_mode": args.pose_selection_mode,
        "selected_rank": args.pose_candidate_rank,
        "consensus_rotation_deg": args.consensus_rotation_deg,
        "consensus_translation_m": args.consensus_translation_m,
        "candidates": serializable_bank,
    }, indent=2) + "\n", encoding="utf-8")
    print(f"[selection] mode={args.pose_selection_mode} serial={best_serial} "
          f"iou={mean_iou:.4f} quality={chosen['pnp_quality']:.3f} "
          f"consensus={chosen['consensus']:.3f} hybrid={chosen['hybrid_score']:.3f}", flush=True)

    pose_final = pose_pre
    sil_loss = None
    sil_sec = 0.0
    if not args.skip_silhouette:
        sil_views = [
            {"mask": masks[s].astype(np.uint8) * 255,
             "K": intrinsics[s].astype(np.float32),
             "extrinsic": extrinsics[s]}
            for s in serials
        ]
        t0 = time.perf_counter()
        pose_final, sil_loss = sil.optimize(
            pose_pre, sil_views, iters=args.silhouette_iters, lr=0.002, antialias=True,
        )
        sil_sec = time.perf_counter() - t0

    np.save(output_dir / "init_pose_world.npy", pose_final)
    np.save(output_dir / "init_pose_world_pre_silhouette.npy", pose_pre)
    np.savez(output_dir / "per_view_poses_world.npz", **candidates)
    result = {
        "capture_dir": str(capture_dir), "frame_dir": str(frame_dir),
        "mesh": str(mesh_path), "object_name": object_name,
        "num_input_views": len(serials), "num_foundpose_candidates": len(candidates),
        "iou_best_serial": best_serial, "iou_mean": float(mean_iou),
        "pose_selection_mode": args.pose_selection_mode,
        "pose_candidate_rank": args.pose_candidate_rank,
        "candidate_bank": "candidate_bank.json",
        "foundpose_sec": foundpose_sec, "silhouette_sec": sil_sec,
        "silhouette_loss": None if sil_loss is None else float(sil_loss),
        "init_pose_world": pose_final.tolist(),
    }
    with open(output_dir / "result.json", "w", encoding="utf-8") as f:
        json.dump(result, f, indent=2)
    print(f"[done] {output_dir / 'init_pose_world.npy'}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
