#!/usr/bin/env python3
"""Initialize one object world pose from a capture-format frame.

This is the bridge between a raw capture episode (``videos/`` + ``cam_param/``)
and the FoundPose/GoTrack pipeline.  It consumes the PNGs written by
``src/process/mask.py --frame-index``:

    <frame-dir>/images/<serial>.png
    <frame-dir>/masks/<serial>.png

It estimates a FoundPose candidate independently for each visible camera,
selects a single world-frame pose by cross-view silhouette IoU, optionally
refines it, and saves ``init_pose_world.npy`` for GoTrack frame 0.

Run in the ``gotrack`` conda environment.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
from pathlib import Path

import cv2
import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

os.environ.setdefault("PYOPENGL_PLATFORM", "egl")
os.environ.setdefault("EGL_PLATFORM", "surfaceless")


def _as_4x4(value: object) -> np.ndarray:
    pose = np.asarray(value, dtype=np.float64)
    if pose.shape == (3, 4):
        pose = np.vstack([pose, [0.0, 0.0, 0.0, 1.0]])
    if pose.shape != (4, 4):
        raise ValueError(f"Expected a 3x4 or 4x4 extrinsic, got {pose.shape}")
    return pose


def load_frame_inputs(capture_dir: Path, frame_dir: Path):
    """Return RGB images, boolean masks, K matrices, and world-to-camera poses."""
    with open(capture_dir / "cam_param" / "intrinsics.json", encoding="utf-8") as f:
        intr_raw = json.load(f)
    with open(capture_dir / "cam_param" / "extrinsics.json", encoding="utf-8") as f:
        extr_raw = json.load(f)

    images_dir = frame_dir / "images"
    masks_dir = frame_dir / "masks"
    if not images_dir.is_dir() or not masks_dir.is_dir():
        raise FileNotFoundError(
            f"Expected images/ and masks/ under {frame_dir}. "
            "Run src/process/mask.py --frame-index first."
        )

    images_rgb: dict[str, np.ndarray] = {}
    masks_bool: dict[str, np.ndarray] = {}
    intrinsics: dict[str, np.ndarray] = {}
    extrinsics: dict[str, np.ndarray] = {}
    for image_path in sorted(images_dir.glob("*.png")):
        serial = image_path.stem
        mask_path = masks_dir / image_path.name
        if serial not in intr_raw or serial not in extr_raw or not mask_path.exists():
            continue
        bgr = cv2.imread(str(image_path), cv2.IMREAD_COLOR)
        mask = cv2.imread(str(mask_path), cv2.IMREAD_GRAYSCALE)
        if bgr is None or mask is None or mask.shape != bgr.shape[:2]:
            continue
        if int((mask > 127).sum()) == 0:
            continue
        images_rgb[serial] = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
        masks_bool[serial] = mask > 127
        intrinsics[serial] = np.asarray(
            intr_raw[serial]["intrinsics_undistort"], dtype=np.float64,
        ).reshape(3, 3)
        extrinsics[serial] = _as_4x4(extr_raw[serial])

    if not images_rgb:
        raise RuntimeError("No valid image/mask/calibration triples found.")
    first = next(iter(images_rgb.values()))
    return images_rgb, masks_bool, intrinsics, extrinsics, first.shape[:2]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--capture-dir", required=True,
                        help="Capture episode containing cam_param/.")
    parser.add_argument("--frame-dir", default=None,
                        help="Directory generated by mask.py --frame-index. Default: frame 0 output.")
    parser.add_argument("--mesh", required=True, help="Object mesh path (.obj/.ply/.glb).")
    parser.add_argument("--object-name", default=None,
                        help="FoundPose asset tag. Default: capture directory parent name.")
    parser.add_argument("--output-dir", default=None,
                        help="Default: <frame-dir>/foundpose_init/")
    parser.add_argument("--assets-root", default=None,
                        help="Default: <mesh parent>/foundpose_assets when present, otherwise "
                             "<capture parent>/foundpose_assets.")
    parser.add_argument("--device", default="cuda:0")
    parser.add_argument("--force-onboard", action="store_true")
    parser.add_argument("--skip-silhouette", action="store_true",
                        help="Save cross-view IoU pose without silhouette refinement.")
    parser.add_argument("--silhouette-iters", type=int, default=100)
    parser.add_argument("--pose-selection-mode", choices=("silhouette", "consensus", "hybrid", "global"),
                        default="silhouette",
                        help="Candidate selector. global adds coarse SO(3) search and multi-start silhouette refinement.")
    parser.add_argument("--pose-candidate-rank", type=int, default=0,
                        help="Use this zero-based rank from the selected candidate bank; useful for case studies.")
    parser.add_argument("--candidate-bank-size", type=int, default=3,
                        help="How many ranked candidates to save for inspection.")
    parser.add_argument("--per-view-candidates", type=int, default=5,
                        help=("FoundPose PnP alternatives retained per camera in global mode. "
                              "They reuse the same DINO features; default 5."))
    parser.add_argument("--consensus-rotation-deg", type=float, default=25.0)
    parser.add_argument("--consensus-translation-m", type=float, default=0.06)
    parser.add_argument("--global-rotation-count", type=int, default=256,
                        help="Deterministic SO(3) hypotheses used by global mode.")
    parser.add_argument("--global-coarse-max-side", type=int, default=160,
                        help="Maximum mask side for global coarse silhouette scoring.")
    parser.add_argument("--global-refine-top-k", type=int, default=5,
                        help="Coarse global hypotheses receiving full silhouette refinement.")
    parser.add_argument("--global-min-rotation-separation-deg", type=float, default=35.0,
                        help="Minimum rotation distance between coarse hypotheses sent to refinement.")
    parser.add_argument("--global-asymmetry-refine-top-k", type=int, default=12,
                        help="Diverse hypotheses refined only after near-symmetry is detected.")
    parser.add_argument("--global-asymmetry-max-side", type=int, default=512,
                        help="Resolution for symmetry-breaking silhouette reranking.")
    parser.add_argument("--global-asymmetry-score-margin", type=float, default=0.005,
                        help="Robust-IoU margin that triggers symmetry-breaking reranking.")
    parser.add_argument("--global-asymmetry-weight", type=float, default=0.7)
    parser.add_argument(
        "--global-asymmetry-force",
        action="store_true",
        help=("Always refine and asymmetry-rerank the diverse global hypothesis pool. "
              "Useful when a small symmetry-breaking feature is known to be missed "
              "by the automatic ambiguity trigger."),
    )
    parser.add_argument("--global-dino-rerank", action=argparse.BooleanOptionalAction, default=False,
                        help=("Experimental: use FoundPose's cached cross-view DINO correspondences "
                              "as a tie-break among near-equal silhouette candidates."))
    parser.add_argument("--global-dino-score-margin", type=float, default=0.02,
                        help="Only candidates this close to the best mask score are DINO-reranked.")
    parser.add_argument("--global-dino-inlier-threshold-px", type=float, default=10.0,
                        help="Soft reprojection threshold in FoundPose crop pixels.")
    args = parser.parse_args()
    if args.per_view_candidates < 1:
        raise ValueError("--per-view-candidates must be positive")
    if args.pose_selection_mode == "global" and args.skip_silhouette:
        raise ValueError("--skip-silhouette is incompatible with --pose-selection-mode global")

    capture_dir = Path(args.capture_dir).expanduser().resolve()
    frame_dir = (Path(args.frame_dir).expanduser().resolve() if args.frame_dir else
                 capture_dir / "foundpose_frame_000000")
    mesh_path = Path(args.mesh).expanduser().resolve()
    output_dir = (Path(args.output_dir).expanduser().resolve() if args.output_dir else
                  frame_dir / "foundpose_init")
    # A campaign-local cache matches its calibration family. Fall back to the
    # mesh-local cache for existing captures that have no campaign cache yet.
    campaign_assets_root = capture_dir.parent / "foundpose_assets"
    mesh_assets_root = mesh_path.parent / "foundpose_assets"
    assets_root = (
        Path(args.assets_root).expanduser().resolve() if args.assets_root else
        mesh_assets_root if mesh_assets_root.is_dir() else
        campaign_assets_root
    )
    object_name = args.object_name or capture_dir.parent.name
    if not mesh_path.is_file():
        raise FileNotFoundError(f"Mesh not found: {mesh_path}")

    images, masks, intrinsics, extrinsics, (height, width) = load_frame_inputs(
        capture_dir, frame_dir,
    )
    serials = sorted(images)
    output_dir.mkdir(parents=True, exist_ok=True)
    print(f"[inputs] {len(serials)} valid views, {width}x{height}; object={object_name}", flush=True)

    from autodex.perception.foundpose_init import FoundPoseInit
    from autodex.perception.pose_select import (
        build_global_pose_hypotheses,
        compute_cross_view_iou,
        has_rotation_ambiguous_top_poses,
        rank_pose_candidates,
        score_pose_hypotheses_by_dino_reprojection,
        score_pose_hypotheses_by_asymmetry,
        score_pose_hypotheses_by_iou,
        select_diverse_pose_hypotheses,
        select_best_pose_by_iou,
    )

    init = FoundPoseInit(
        mesh_path=str(mesh_path),
        assets_root=str(assets_root),
        obj_name=object_name,
        object_id=1,
        device=args.device,
        reference_intrinsics_json=str(capture_dir / "cam_param" / "intrinsics.json"),
        reference_camera_id=serials[0],
        force_onboard=args.force_onboard,
    )
    t0 = time.perf_counter()
    per_view = init.estimate_per_view(
        images, masks, intrinsics, extrinsics,
        max_pose_candidates_per_view=(
            args.per_view_candidates if args.pose_selection_mode == "global" else 1
        ),
    )
    foundpose_sec = time.perf_counter() - t0
    candidates = {s: item["pose_world"] for s, item in per_view.items() if item is not None}
    if not candidates:
        raise RuntimeError("FoundPose failed in every camera view.")
    print(f"[foundpose] {len(candidates)}/{len(serials)} candidate poses ({foundpose_sec:.1f}s)", flush=True)
    expanded_candidates: dict[str, np.ndarray] = {}
    expanded_metadata: dict[str, dict[str, object]] = {}
    for serial, item in per_view.items():
        if item is None:
            continue
        for candidate in item.get("pose_candidates", []):
            rank = int(candidate.get("candidate_rank", 0))
            key = f"{serial}#{rank}"
            expanded_candidates[key] = np.asarray(candidate["pose_world"], dtype=np.float64)
            expanded_metadata[key] = {
                "foundpose_camera": serial,
                "foundpose_candidate_rank": rank,
                "foundpose_quality": float(candidate.get("quality", 0.0)),
                "foundpose_inliers": int(candidate.get("inliers", 0)),
                "foundpose_template_id": int(candidate.get("template_id", -1)),
                "foundpose_corresp_id": int(candidate.get("corresp_id", -1)),
            }
    if args.pose_selection_mode == "global":
        print(f"[foundpose] retained {len(expanded_candidates)} PnP candidates "
              f"from {len(candidates)} views", flush=True)

    from autodex.perception.silhouette import SilhouetteOptimizer
    sil = SilhouetteOptimizer(str(mesh_path), device=args.device)
    best_serial, legacy_pose, legacy_mean_iou, per_candidate_iou = select_best_pose_by_iou(
        candidates=candidates,
        masks=masks,
        intrinsics=intrinsics,
        extrinsics=extrinsics,
        H=height,
        W=width,
        glctx=sil.glctx,
        mesh_tensors=sil.mesh_tensors,
    )
    if legacy_pose is None:
        raise RuntimeError("Cross-view IoU pose selection failed.")

    candidate_bank = rank_pose_candidates(
        candidates=candidates,
        pnp_quality={serial: float(per_view[serial]["quality"]) for serial in candidates},
        iou_scores=per_candidate_iou,
        consensus_rotation_deg=args.consensus_rotation_deg,
        consensus_translation_m=args.consensus_translation_m,
    )
    sil_views = [
        {"mask": masks[s].astype(np.uint8) * 255,
         "K": intrinsics[s].astype(np.float32),
         "extrinsic": extrinsics[s]}
        for s in serials
    ]
    global_silhouette_sec = 0.0
    asymmetry_applied = False
    dino_rerank_applied = False
    if args.pose_selection_mode == "global":
        if (args.global_rotation_count < 1 or args.global_coarse_max_side < 32
                or args.global_refine_top_k < 1 or args.global_min_rotation_separation_deg < 0
                or args.global_asymmetry_refine_top_k < args.global_refine_top_k
                or args.global_asymmetry_max_side < 32 or args.global_asymmetry_score_margin < 0
                or not 0 <= args.global_asymmetry_weight <= 1
                or args.global_dino_score_margin < 0
                or args.global_dino_inlier_threshold_px <= 0):
            raise ValueError("global search parameters must be positive")
        hypotheses = build_global_pose_hypotheses(
            expanded_candidates,
            rotation_count=args.global_rotation_count,
            translation_candidates=candidates,
            candidate_metadata=expanded_metadata,
        )
        t_global = time.perf_counter()
        coarse_ranked = score_pose_hypotheses_by_iou(
            hypotheses=hypotheses,
            masks=masks,
            intrinsics=intrinsics,
            extrinsics=extrinsics,
            glctx=sil.glctx,
            mesh_tensors=sil.mesh_tensors,
            max_side=args.global_coarse_max_side,
        )
        for coarse_rank, item in enumerate(coarse_ranked):
            item["coarse_rank"] = coarse_rank
        refine_seed_pool = select_diverse_pose_hypotheses(
            coarse_ranked,
            count=min(args.global_asymmetry_refine_top_k, len(coarse_ranked)),
            min_rotation_deg=args.global_min_rotation_separation_deg,
            min_translation_m=0.02,
        )
        coarse_bank = [{
            "source_serial": str(item["source"]),
            "pose_world": np.asarray(item["pose_world"]).tolist(),
            "mean_iou": float(item["coarse_mean_iou"]),
            "robust_iou": float(item["coarse_robust_iou"]),
            "pnp_quality": float(item.get("foundpose_quality", 0.0)),
            "consensus": 0.0,
            "hybrid_score": float(item["coarse_robust_iou"]),
            "coarse_rank": int(item["coarse_rank"]),
            **{key: item[key] for key in (
                "foundpose_camera", "foundpose_candidate_rank", "foundpose_quality",
                "foundpose_inliers", "foundpose_template_id", "foundpose_corresp_id",
            ) if key in item},
        } for item in refine_seed_pool]
        (output_dir / "global_coarse_bank.json").write_text(json.dumps({
            "selection_mode": "global_coarse",
            "selected_rank": 0,
            "candidates": coarse_bank,
        }, indent=2) + "\n", encoding="utf-8")
        def refine_seed(item: dict[str, object]) -> dict[str, object]:
            seed_pose = np.asarray(item["pose_world"], dtype=np.float64)
            refined_pose, refined_loss = sil.optimize(
                seed_pose, sil_views, iters=args.silhouette_iters, lr=0.002, antialias=True,
            )
            refined_iou, refined_per_view = compute_cross_view_iou(
                refined_pose, masks, intrinsics, extrinsics, height, width,
                sil.glctx, sil.mesh_tensors,
            )
            refined_values = np.sort(np.asarray(list(refined_per_view.values()), dtype=np.float64))
            trim = int(np.floor(len(refined_values) * 0.15))
            refined_kept = refined_values[trim:len(refined_values) - trim] if trim > 0 else refined_values
            refined_robust_iou = float(refined_kept.mean()) if len(refined_kept) else float(refined_iou)
            return {
                "source_serial": str(item["source"]),
                "pose_world": refined_pose,
                "pose_world_coarse": seed_pose,
                "mean_iou": float(refined_iou),
                "robust_iou": refined_robust_iou,
                "pnp_quality": float(item.get("foundpose_quality", 0.0)),
                "consensus": 0.0,
                "hybrid_score": refined_robust_iou,
                "coarse_rank": int(item["coarse_rank"]),
                "coarse_mean_iou": float(item["coarse_mean_iou"]),
                "coarse_robust_iou": float(item["coarse_robust_iou"]),
                "silhouette_loss": float(refined_loss),
                **{key: item[key] for key in (
                    "foundpose_camera", "foundpose_candidate_rank", "foundpose_quality",
                    "foundpose_inliers", "foundpose_template_id", "foundpose_corresp_id",
                ) if key in item},
            }

        initial_count = min(args.global_refine_top_k, len(refine_seed_pool))
        print(f"[global] hypotheses={len(hypotheses)} refine_top_k={initial_count}", flush=True)
        refined = [refine_seed(item) for item in refine_seed_pool[:initial_count]]
        refined_ranked = sorted(refined, key=lambda item: float(item["robust_iou"]), reverse=True)
        asymmetry_detected = has_rotation_ambiguous_top_poses(
            refined_ranked,
            score_margin=args.global_asymmetry_score_margin,
            min_rotation_deg=25.0,
        )
        asymmetry_applied = args.global_asymmetry_force or asymmetry_detected
        if asymmetry_applied:
            extra_seeds = refine_seed_pool[initial_count:]
            trigger = "forced" if args.global_asymmetry_force else "detected"
            print(
                f"[global] rotation ambiguity {trigger}; "
                f"refining {len(extra_seeds)} extra hypotheses",
                flush=True,
            )
            refined.extend(refine_seed(item) for item in extra_seeds)
            refined_ranked = score_pose_hypotheses_by_asymmetry(
                refined,
                masks=masks,
                intrinsics=intrinsics,
                extrinsics=extrinsics,
                glctx=sil.glctx,
                mesh_tensors=sil.mesh_tensors,
                max_side=args.global_asymmetry_max_side,
                asymmetry_weight=args.global_asymmetry_weight,
            )
        if args.global_dino_rerank:
            appearance_evidence = {
                serial: item["appearance_evidence"]
                for serial, item in per_view.items()
                if item is not None and item.get("appearance_evidence")
            }
            dino_scored = score_pose_hypotheses_by_dino_reprojection(
                refined_ranked,
                appearance_evidence=appearance_evidence,
                inlier_threshold_px=args.global_dino_inlier_threshold_px,
            )

            def mask_score(item: dict[str, object]) -> float:
                return float(item.get(
                    "asymmetry_combined_score", item.get("robust_iou", 0.0),
                ))

            best_mask_score = max((mask_score(item) for item in dino_scored), default=0.0)
            eligible = [
                item for item in dino_scored
                if best_mask_score - mask_score(item) <= args.global_dino_score_margin
                and int(item.get("dino_valid_views", 0)) >= 3
            ]
            eligible_ids = {id(item) for item in eligible}
            remainder = sorted(
                (item for item in dino_scored if id(item) not in eligible_ids),
                key=mask_score,
                reverse=True,
            )
            if len(eligible) >= 2:
                eligible.sort(
                    key=lambda item: float(item["dino_reprojection_score"]), reverse=True,
                )
                refined_ranked = eligible + remainder
                dino_rerank_applied = True
                print(
                    f"[global] DINO reprojection reranked {len(eligible)} mask-tied hypotheses; "
                    f"winner={eligible[0]['source_serial']} "
                    f"score={eligible[0]['dino_reprojection_score']:.3f}",
                    flush=True,
                )
            else:
                # Keep the original mask ordering when DINO evidence cannot
                # compare at least two well-supported hypotheses.
                refined_ranked = sorted(dino_scored, key=mask_score, reverse=True)
        global_silhouette_sec = time.perf_counter() - t_global
        selected = select_diverse_pose_hypotheses(
            refined_ranked,
            count=min(max(args.candidate_bank_size, args.pose_candidate_rank + 1), len(refined_ranked)),
            min_rotation_deg=10.0,
            min_translation_m=0.01,
        )
    elif args.pose_selection_mode == "silhouette":
        selected = sorted(candidate_bank, key=lambda item: item["mean_iou"], reverse=True)
    elif args.pose_selection_mode == "consensus":
        selected = sorted(candidate_bank, key=lambda item: item["consensus"], reverse=True)
    else:
        selected = sorted(candidate_bank, key=lambda item: item["hybrid_score"], reverse=True)
    if args.pose_candidate_rank < 0 or args.pose_candidate_rank >= len(selected):
        raise ValueError(f"--pose-candidate-rank must be in [0, {len(selected) - 1}]")
    chosen = selected[args.pose_candidate_rank]
    pose_pre = np.asarray(chosen.get("pose_world_coarse", chosen["pose_world"]), dtype=np.float64)
    mean_iou = float(chosen["mean_iou"])
    best_serial = str(chosen["source_serial"])
    serializable_bank = [{
        key: (value.tolist() if isinstance(value, np.ndarray) else value)
        for key, value in item.items()
    } for item in selected[:max(1, args.candidate_bank_size, args.pose_candidate_rank + 1)]]
    (output_dir / "candidate_bank.json").write_text(json.dumps({
        "selection_mode": args.pose_selection_mode,
        "selected_rank": args.pose_candidate_rank,
        "consensus_rotation_deg": args.consensus_rotation_deg,
        "consensus_translation_m": args.consensus_translation_m,
        "candidates": serializable_bank,
    }, indent=2) + "\n", encoding="utf-8")
    print(f"[selection] mode={args.pose_selection_mode} serial={best_serial} "
          f"iou={mean_iou:.4f} quality={chosen['pnp_quality']:.3f} "
          f"consensus={chosen['consensus']:.3f} hybrid={chosen['hybrid_score']:.3f} "
          f"asymmetry={chosen.get('asymmetry_combined_score', float('nan')):.3f} "
          f"dino={chosen.get('dino_reprojection_score', float('nan')):.3f}", flush=True)

    pose_final = np.asarray(chosen["pose_world"], dtype=np.float64) if args.pose_selection_mode == "global" else pose_pre
    sil_loss = float(chosen["silhouette_loss"]) if args.pose_selection_mode == "global" else None
    sil_sec = global_silhouette_sec
    if not args.skip_silhouette and args.pose_selection_mode != "global":
        t0 = time.perf_counter()
        pose_final, sil_loss = sil.optimize(
            pose_pre, sil_views, iters=args.silhouette_iters, lr=0.002, antialias=True,
        )
        sil_sec = time.perf_counter() - t0

    np.save(output_dir / "init_pose_world.npy", pose_final)
    np.save(output_dir / "init_pose_world_pre_silhouette.npy", pose_pre)
    np.savez(output_dir / "per_view_poses_world.npz", **candidates)
    if args.pose_selection_mode == "global":
        np.savez(output_dir / "per_view_pose_candidates_world.npz", **expanded_candidates)
    result = {
        "capture_dir": str(capture_dir), "frame_dir": str(frame_dir),
        "mesh": str(mesh_path), "object_name": object_name,
        "num_input_views": len(serials), "num_foundpose_candidates": len(candidates),
        "num_foundpose_pnp_candidates": len(expanded_candidates),
        "per_view_candidates": args.per_view_candidates if args.pose_selection_mode == "global" else 1,
        "iou_best_serial": best_serial, "iou_mean": float(mean_iou),
        "pose_selection_mode": args.pose_selection_mode,
        "pose_candidate_rank": args.pose_candidate_rank,
        "global_rotation_count": args.global_rotation_count if args.pose_selection_mode == "global" else None,
        "global_refine_top_k": args.global_refine_top_k if args.pose_selection_mode == "global" else None,
        "global_asymmetry_forced": args.global_asymmetry_force if args.pose_selection_mode == "global" else None,
        "global_asymmetry_detected": asymmetry_detected if args.pose_selection_mode == "global" else None,
        "global_asymmetry_applied": asymmetry_applied if args.pose_selection_mode == "global" else None,
        "global_dino_rerank_requested": args.global_dino_rerank if args.pose_selection_mode == "global" else None,
        "global_dino_rerank_applied": dino_rerank_applied if args.pose_selection_mode == "global" else None,
        "global_dino_score_margin": args.global_dino_score_margin if args.pose_selection_mode == "global" else None,
        "global_coarse_bank": "global_coarse_bank.json" if args.pose_selection_mode == "global" else None,
        "candidate_bank": "candidate_bank.json",
        "foundpose_sec": foundpose_sec, "silhouette_sec": sil_sec,
        "silhouette_loss": None if sil_loss is None else float(sil_loss),
        "init_pose_world": pose_final.tolist(),
    }
    with open(output_dir / "result.json", "w", encoding="utf-8") as f:
        json.dump(result, f, indent=2)
    print(f"[done] {output_dir / 'init_pose_world.npy'}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
